### ISSUE TITLE
Add illustrator file that contains the icons

### ISSUE THREAD

**Issue by thclark** [windpioneers/wp-public#2]
### Use Case

We want to be able to add icons to the original source of truth for the icon designs. This means we need to have access to the `.ai` (or whatever other svg editor program was used) file.

### Current state

No access (not in the repo)

### Proposed Solution

Add hte illustrator file to the repo so we can edit the icon set and regenerate PNGs where necessary (@shashankanp to nag Seema for it when she's back from leave)

**Comment by shashankanp** [comment]
Added the file into the public folder
